In [12]:
import numpy as np

demand1 = np.array([32700, 27375, 21800, 27375], dtype=np.float64)
demand2 = np.array([16350, 13625, 10900, 13625], dtype=np.float64)
demand3 = np.array([11250, 9375, 7500, 9375], dtype=np.float64)
demand4 = np.array([10125, 8438, 6750, 8438], dtype=np.float64)
demand5 = np.array([4575, 3813, 3050, 3563], dtype=np.float64)

demand4/30/100*1.3*6

array([26.325 , 21.9388, 17.55  , 21.9388])

In [7]:
import pandas as pd
import numpy as np 
from runGA import SupplyChainEnv

results = pd.read_excel("Results/GA/results.xlsx")


array = np.fromstring(results.iloc[0,2].strip("[]"), sep=" ")


env = SupplyChainEnv()
reward = env.step(array)

# Exibir resultado
print(f"TotalCost = {env.statistics['TotalCost']}")
print(f"StockCost = {env.statistics['StockCost']}")
print(f"emissionsCost = {env.statistics['emissionsCost']}")
print(f"LostSalesCost = {env.statistics['LostSalesCost']}")


TotalCost = 413.13959070178606
StockCost = 377.2581230405423
emissionsCost = 35.88146766124378
LostSalesCost = 0.0


In [2]:
import numpy as np

a = np.array([10, 20, 0, 40, 0])  # Valores finais
b = np.array([2,  0,  0, 20, 5])  # Valores iniciais

# Cálculo da variação relativa: (a - b) / b
variação = np.where(
    b == 0, 
    np.where(a == 0, 0, 1),  # Se b == 0 e a == 0 → 0%, senão → 100% (ou 1)
    (a / b ) -1  # Caso normal
)

a.copy()


C:\Users\djonq\AppData\Local\Temp\ipykernel_3744\2007204041.py:10: RuntimeWarning: divide by zero encountered in divide
  (a / b ) -1  # Caso normal
C:\Users\djonq\AppData\Local\Temp\ipykernel_3744\2007204041.py:10: RuntimeWarning: invalid value encountered in divide
  (a / b ) -1  # Caso normal


array([10, 20,  0, 40,  0])

In [1]:
import numpy as np

a = np.array([0,10,30])

np.maximum(a, 20)

array([20, 20, 30])

In [2]:
import numpy as np

a = np.full((5, 4), 300, dtype=float)
b = np.array([i for i in range(20)], dtype=float)

c= a.flatten()*b

C = c.reshape((5,4))

C.size

20

In [3]:
import numpy as np
a = np.full(5, 1000, dtype=int)

a*0.4

array([400., 400., 400., 400., 400.])

In [21]:
d[:-1] += 65
d

array([165, 265, 365, 400])

In [11]:
def calcular_producao_possivel(order, stock):
    # Calcula a produção possível para cada item
    producao_possivel = [min(o, s) for o, s in zip(order, stock)]
    return producao_possivel

# Exemplo de uso
order = [300, 200, 100]
stock = [500, 100, 50]

# Chama a função para calcular a produção possível
producao_possivel = calcular_producao_possivel(order, stock)

print(producao_possivel)


[300, 100, 50]


In [1]:
import numpy as np

np.array([])


array([], dtype=float64)